### PR TITLE
Fix name.

### PR DESCRIPTION
**Pull request by kevincox**

### CODE REVIEW

**Review by SomebodyLikeEveryBody — APPROVED** [review]

**Review by SomebodyLikeEveryBody — COMMENTED** [review]
Oops Thanks for the correction, I can't believe I passed by this, sorry for that.
By the way I'm working on a way way way better interface to do this currently.
I dit this first ugly version very fast to play Ricochet Robot with friends and modify the map easier than I did. 
I will upload the new version next week, and in the near future the purpose would be to have a full front-end solver with the solver algorithm in a .js file if it is technically possible. I would be very proud if you forked the V2 map custom project to implement it in your website :)

**Comment by kevincox** [comment]
On 01/08/2020 11:01, Victor Vague wrote:
> Oops Thanks for the correction, I can't believe I passed by this, 
> sorry for that.

No problem :)

> By the way I'm working on a way way way better interface to do this 
> currently.
> I dit this first ugly version very fast to play Ricochet Robot with 
> friends and modify the map easily than I did.
> I will upload the new version next week, and in the near future the 
> purpose would be to have a full front-end solver with the solver 
> algorithm in a .js file if it is technically possible. I would be very 
> proud if you forked the project to implement it in your website :)
>
I'm a little confused, my website is already a frontend solver, is there 
is missing feature that you are interested in? It would probably be 
easier to add the feature instead of rewriting.

In fact I was going to suggest that if you are going to rewrite the the board 
creation UI, it may be easier to add it to the existing site as it already has primitives for 
adding and removing walls. (For example it handles adding south walls by 
adding a north wall to the cell bellow) as well as other features such 
as rotation that may be useful.

If you are interested in writing your own solver for fun (it is a very 
cool project) I just want to warn you that you will have a hard time 
implementing it in javascript. Right now one of the biggest limitations 
for solving hard games is the memory in which we cache previously 
visited states. Avoiding re-testing existing states is important to both 
performance and memory use (technically you could only check against the 
queue which would solve the memory use but then you have more 
performance issues). I have managed to tune my solver to only use 8 
bytes for each visited state (plus a bit of hash table overhead). This 
means that you can solve just about any puzzle I have come across, even on 
mobile. But even using twice that much means that some puzzles will run out
of memory. If you want to do this in javascript you will have a hard 
time hitting that number as (AFAIK) object keys are represented as 
strings (or dense arrays for small integer keys) so you will have at 
least 8 bytes for the key, then you will need a value which will 
probably end up as 8 bytes. So you will have a hard time solving 
difficult games on phones.

It isn't hard to make a solver that solves the easy (<10 moves are 
usually quite easy) puzzles quickly, but you might want to try a more 
efficient language if you want to be able to solve everything.

Hope that is helpful!

**Comment by SomebodyLikeEveryBody** [comment]
> I'm a little confused, my website is already a frontend solver, is there
> is missing feature that you are interested in? It would probably be
> easier to add the feature instead of rewriting.

In fact, the website is awesome but to be honest it doesn't fit in my screen and I have to scroll down to see the entire board instead of a responsive display.

> I'm a little confused, my website is already a frontend solver, is there
> is missing feature that you are interested in? It would probably be
> easier to add the feature instead of rewriting.

Moreover, I found the utilisation and the position of the buttons not very intuitive to my brain at first sight (the animation launches directly and I prefer to have something like "It is solved, do you want the number of steps ? " --> yes --> "the number of steps is 7, do you want to see the solution ?" --> yes --> no animation and we can launch animation or see each steps, instead of have all given at the same time), so I started to work on another view which is the vue of the V2 of the map formatter (https://somebodylikeeverybody.github.io/Ricochet_Robot_map_formatter/). And then I wondered if it was possible to have a solver with only javascript so I could use github Pages to store the project without need of a server and use it everywhere. 

But actually it is much an intellectual an fun purpose than a real need because with a finished map formatter and your website I can already train myself and play with friends with the solver ^^.

> In fact I was going to suggest that if you are going to rewrite the the board
> creation UI, it may be easier to add it to the existing site as it already has primitives for
> adding and removing walls. (For example it handles adding south walls by
> adding a north wall to the cell bellow) as well as other features such
> as rotation that may be useful.

Yes I will probably do that in a time :p

> If you are interested in writing your own solver for fun (it is a very
> cool project) I just want to warn you that you will have a hard time
> implementing it in javascript. Right now one of the biggest limitations
> for solving hard games is the memory in which we cache previously
> visited states. Avoiding re-testing existing states is important to both
> performance and memory use (technically you could only check against the
> queue which would solve the memory use but then you have more
> performance issues). I have managed to tune my solver to only use 8
> bytes for each visited state (plus a bit of hash table overhead). This
> means that you can solve just about any puzzle I have come across, even on
> mobile. But even using twice that much means that some puzzles will run out
> of memory. If you want to do this in javascript you will have a hard
> time hitting that number as (AFAIK) object keys are represented as
> strings (or dense arrays for small integer keys) so you will have at
> least 8 bytes for the key, then you will need a value which will
> probably end up as 8 bytes. So you will have a hard time solving
> difficult games on phones.
> 
> It isn't hard to make a solver that solves the easy (<10 moves are
> usually quite easy) puzzles quickly, but you might want to try a more
> efficient language if you want to be able to solve everything.

Thank you very much for your advices it helps me a lot !

**Comment by kevincox** [comment]
On Mon., Aug. 3, 2020, 12:23 Victor Vague, <notifications@github.com> wrote:

> In fact, the website is awesome but to be honest it doesn't fit in my
> screen and I have to scroll down to see the entire board instead of a
> responsive display.
>

The board should be sized to fit on your screen. However if you want to use
the buttons at the bottom they may be off screen.  It could be better, just
needs some polish put it.

> I found the utilisation and the position of the buttons not very
intuitive to my brain at first sight...

I agree, the UX could be better (although I'm not sure I quite understand
your idea here, it seems like a lot of clicks instead of just showing the
info). That is why I was hoping you to contribute better UI 😉. I'm not
much of a UI dev so I just made something simple that would work. It's no
secret that it can be improved (or replaced with something better).

> And then I wondered if it was possible to have a solver with only
> javascript so I could use github Pages to store the project without need of
> a server and use it everywhere.
>
The current site is the same way. I think you are a bit confused how it
works. The only thing stopping it from being hosted on GitHub pages is the
build step. (Of course you could build it in CI and push the result to the
repo if you wanted to 🤷‍♀️, but that seems like more work for no benefit)

**Pull request merged**
